[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "jupyter-archive>=3.4.0",
    "librosa>=0.11.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "sentence-transformers>=5.1.2",
    "soundfile>=0.13.1",
    "tensorflow>=2.20.0",
    "tensorflow-hub>=0.16.1",
    "tf-keras>=2.20.1",
    "tqdm>=4.67.1",
]
